/**
 * Read-only roadmap snapshot: the whole board as ONE self-contained HTML file
 * (inline styles, no scripts, no external requests) — safe to email, attach,
 * or publish for stakeholders who don't run the app. Pure string rendering
 * over data already in memory.
 */

import { summarizeInitiatives } from "./initiatives";
import {
  LANES,
  LANE_LABELS,
  type Lane,
  type Project,
  type RoadmapItemView,
} from "./schema/types";

const LANE_COLORS: Record<Lane, string> = {
  idea: "#0369a1",
  ranked: "#b45309",
  development: "#4f46e5",
  done: "#15803d",
};

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function renderSnapshotHtml(
  project: Project,
  items: RoadmapItemView[],
  generatedAt = new Date().toISOString(),
): string {
  const byLane = (lane: Lane) =>
    items.filter((it) => it.status === lane).sort((a, b) => b.priority - a.priority);
  const initiatives = summarizeInitiatives(items).filter((i) => i.total >= 2);
  const accent = project.color || "#4f46e5";
  const done = items.filter((i) => i.status === "done").length;

  const card = (it: RoadmapItemView) => `
    <div class="card">
      <div class="row"><span class="t">${esc(it.title)}</span><span class="prio">${it.priority}</span></div>
      <div class="meta">${esc(it.category)}${(it.labels ?? []).map((l) => ` · <span class="lbl">${esc(l)}</span>`).join("")}${it.dueDate ? ` · due ${it.dueDate}` : ""}</div>
      ${it.description ? `<p class="d">${esc(it.description)}</p>` : ""}
    </div>`;

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${esc(project.name)} — roadmap snapshot</title>
<style>
*{box-sizing:border-box;margin:0}
body{font-family:Inter,system-ui,-apple-system,sans-serif;background:#f4f6f8;color:#16181d;padding:34px 22px;line-height:1.5}
.wrap{max-width:1180px;margin:0 auto}
.k{font-family:ui-monospace,Menlo,monospace;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:${accent};font-weight:700}
h1{font-size:28px;letter-spacing:-.01em;margin:6px 0 4px}
.sub{color:#667085;font-size:13.5px;margin-bottom:8px}
.stats{display:flex;gap:22px;margin:14px 0 6px;font-size:13px;color:#667085}
.stats b{color:#0b0d12;font-family:ui-monospace,monospace}
.inits{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0 4px}
.init{font-size:12px;border:1px solid #d9dee7;border-radius:999px;padding:4px 12px;background:#fff;color:#667085}
.init b{color:#0b0d12}
.lanes{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:20px}
@media(max-width:900px){.lanes{grid-template-columns:1fr 1fr}}
@media(max-width:560px){.lanes{grid-template-columns:1fr}}
.lane{background:#eef2f7;border:1px solid #d9dee7;border-radius:14px;padding:12px}
.lh{display:flex;align-items:center;gap:8px;font-weight:700;font-size:13.5px;margin-bottom:10px}
.dot{width:9px;height:9px;border-radius:50%}
.n{margin-left:auto;font-family:ui-monospace,monospace;font-size:12px;color:#667085}
.card{background:#fff;border:1px solid #d9dee7;border-radius:10px;padding:10px 12px;margin-bottom:9px}
.row{display:flex;gap:8px;align-items:baseline}
.t{font-weight:600;font-size:13.5px;color:#0b0d12;flex:1}
.prio{font-family:ui-monospace,monospace;font-weight:700;font-size:13px;color:${accent}}
.meta{font-size:11.5px;color:#98a2b3;margin-top:2px}
.lbl{color:#667085}
.d{font-size:12.5px;color:#667085;margin-top:6px}
footer{margin-top:26px;font-size:12px;color:#98a2b3}
</style></head><body><div class="wrap">
<div class="k">Roadmap snapshot · read-only</div>
<h1>${esc(project.name)}</h1>
${project.description ? `<p class="sub">${esc(project.description)}</p>` : ""}
<div class="stats"><span><b>${items.length}</b> items</span><span><b>${done}</b> done</span><span>generated <b>${generatedAt.slice(0, 16).replace("T", " ")}</b></span></div>
${initiatives.length ? `<div class="inits">${initiatives.map((i) => `<span class="init"><b>${esc(i.label)}</b> ${i.done}/${i.total} · ${i.pctDone}%</span>`).join("")}</div>` : ""}
<div class="lanes">
${LANES.map(
    (lane) => `<div class="lane"><div class="lh"><span class="dot" style="background:${LANE_COLORS[lane]}"></span>${LANE_LABELS[lane]}<span class="n">${byLane(lane).length}</span></div>${byLane(lane).map(card).join("") || `<p class="meta">empty</p>`}</div>`,
  ).join("\n")}
</div>
<footer>Generated by Threlmark — local-first roadmaps · threlmark.com</footer>
</div></body></html>`;
}
